// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParqueDiversion.Entities.Entities
{
    public partial class tbAtracciones
    {
        public tbAtracciones()
        {
            tbFilasAtraccion = new HashSet<tbFilasAtraccion>();
            tbRatings = new HashSet<tbRatings>();
            tbTemporizadores = new HashSet<tbTemporizadores>();
            tbVisitantesAtraccion = new HashSet<tbVisitantesAtraccion>();
        }

        public int atra_ID { get; set; }
        public int? area_ID { get; set; }
        public string atra_Nombre { get; set; }
        public string atra_Descripcion { get; set; }
        public int? regi_ID { get; set; }
        public string atra_ReferenciaUbicacion { get; set; }
        public int? atra_LimitePersonas { get; set; }
        public int? atra_DuracionRonda { get; set; }
        public string atra_Imagen { get; set; }
        public int? atra_Habilitado { get; set; }
        public int? atra_Estado { get; set; }
        public int? atra_UsuarioCreador { get; set; }
        public DateTime? atra_FechaCreacion { get; set; }
        public int? atra_UsuarioModificador { get; set; }
        public DateTime? atra_FechaModificacion { get; set; }

        public virtual tbAreas area { get; set; }
        public virtual tbRegiones regi { get; set; }
        public virtual ICollection<tbFilasAtraccion> tbFilasAtraccion { get; set; }
        public virtual ICollection<tbRatings> tbRatings { get; set; }
        public virtual ICollection<tbTemporizadores> tbTemporizadores { get; set; }
        public virtual ICollection<tbVisitantesAtraccion> tbVisitantesAtraccion { get; set; }
    }
}