// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParqueDiversion.Entities.Entities
{
    public partial class tbFilasPosiciones
    {
        public int fipo_ID { get; set; }
        public int? fiat_ID { get; set; }
        public int? ticl_ID { get; set; }
        public TimeSpan? fipo_HoraIngreso { get; set; }

        public virtual tbFilasAtraccion fiat { get; set; }
        public virtual tbTicketsCliente ticl { get; set; }
    }
}