// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParqueDiversion.Entities.Entities
{
    public partial class tbFilasAtraccion
    {
        public tbFilasAtraccion()
        {
            tbFilasPosiciones = new HashSet<tbFilasPosiciones>();
            tbHistorialFilasPosiciones = new HashSet<tbHistorialFilasPosiciones>();
        }

        public int fiat_ID { get; set; }
        public int? tifi_ID { get; set; }
        public int? atra_ID { get; set; }
        public int? fiat_Habilitado { get; set; }
        public int? fiat_Estado { get; set; }
        public int? fiat_UsuarioCreador { get; set; }
        public DateTime? fiat_FechaCreacion { get; set; }
        public int? fiat_UsuarioModificador { get; set; }
        public DateTime? fiat_FechaModificacion { get; set; }

        public virtual tbAtracciones atra { get; set; }
        public virtual tbTipoFilas tifi { get; set; }
        public virtual ICollection<tbFilasPosiciones> tbFilasPosiciones { get; set; }
        public virtual ICollection<tbHistorialFilasPosiciones> tbHistorialFilasPosiciones { get; set; }
    }
}