// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParqueDiversion.Entities.Entities
{
    public partial class tbHistorialFilasPosiciones
    {
        public int hipo_ID { get; set; }
        public int? fiat_ID { get; set; }
        public int? ticl_ID { get; set; }
        public DateTime? hipo_FechaIngreso { get; set; }
        public int? hipo_Habilitado { get; set; }
        public int? hipo_Estado { get; set; }
        public int? hipo_UsuarioCreador { get; set; }
        public DateTime? hipo_FechaCreacion { get; set; }
        public int? hipo_UsuarioModificador { get; set; }
        public DateTime? hipo_FechaModificacion { get; set; }

        public virtual tbFilasAtraccion fiat { get; set; }
        public virtual tbTicketsCliente ticl { get; set; }
    }
}