// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParqueDiversion.Entities.Entities
{
    public partial class tbInsumosQuiosco
    {
        public int insu_ID { get; set; }
        public int? quio_ID { get; set; }
        public int? golo_ID { get; set; }
        public int? insu_Stock { get; set; }
        public int? insu_Habilitado { get; set; }
        public int? insu_Estado { get; set; }
        public int? insu_UsuarioCreador { get; set; }
        public DateTime? insu_FechaCreacion { get; set; }
        public int? insu_UsuarioModificador { get; set; }
        public DateTime? insu_FechaModificacion { get; set; }

        public virtual tbGolosinas golo { get; set; }
        public virtual tbQuioscos quio { get; set; }
    }
}