// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParqueDiversion.Entities.Entities
{
    public partial class tblCiudades
    {
        public tblCiudades()
        {
            tblEvento = new HashSet<tblEvento>();
        }

        public int CiudadId { get; set; }
        public int DeptoId { get; set; }
        public string CiudadDescripcion { get; set; }
        public string CiudadCreacion { get; set; }
        public string CiudadModificacion { get; set; }
        public DateTime? CiudadUsuFechaCreacion { get; set; }
        public DateTime? CiudadUsuFechaModificacion { get; set; }

        public virtual tblDepto Depto { get; set; }
        public virtual ICollection<tblEvento> tblEvento { get; set; }
    }
}