// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParqueDiversion.Entities.Entities
{
    public partial class tblEmpleado
    {
        public tblEmpleado()
        {
            tblEventoEventoJuezNavigation = new HashSet<tblEvento>();
            tblEventoEventoObservadorNavigation = new HashSet<tblEvento>();
        }

        public int EmpleadoId { get; set; }
        public string EmpleadoNombre { get; set; }
        public string EmpleadoApellido { get; set; }
        public string EmpleadoSexo { get; set; }
        public int EmpleadoEstadoCivil { get; set; }
        public DateTime EmpleadoFechaNac { get; set; }
        public string EmpleadoIdentidad { get; set; }
        public string EmpleadoTelefono { get; set; }
        public string EmpleadoDireccion { get; set; }
        public string EmpleadoCreacion { get; set; }
        public string EmpleadoModificacion { get; set; }
        public DateTime? EmpleadoFechaCreacion { get; set; }
        public DateTime? EmpleadoFechaModificacion { get; set; }
        public string EmpleadoEstado { get; set; }

        public virtual tblEstado EmpleadoEstadoCivilNavigation { get; set; }
        public virtual ICollection<tblEvento> tblEventoEventoJuezNavigation { get; set; }
        public virtual ICollection<tblEvento> tblEventoEventoObservadorNavigation { get; set; }
    }
}