// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParqueDiversion.Entities.Entities
{
    public partial class tblEvento
    {
        public int EventoId { get; set; }
        public DateTime EventoFecha { get; set; }
        public string EventoDuracion { get; set; }
        public int EventoCiudad { get; set; }
        public int EventoDeporte { get; set; }
        public int EventoJuez { get; set; }
        public int EventoObservador { get; set; }
        public string EventoCreacion { get; set; }
        public string EventoModificacion { get; set; }
        public DateTime? EventoFechaCreacion { get; set; }
        public DateTime? EventoFechaModificacion { get; set; }
        public string EvenentoEstado { get; set; }

        public virtual tblCiudades EventoCiudadNavigation { get; set; }
        public virtual tblDeporte EventoDeporteNavigation { get; set; }
        public virtual tblEmpleado EventoJuezNavigation { get; set; }
        public virtual tblEmpleado EventoObservadorNavigation { get; set; }
    }
}