// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParqueDiversion.Entities.Entities
{
    public partial class tblEstado
    {
        public tblEstado()
        {
            tblEmpleado = new HashSet<tblEmpleado>();
            tblParticipante = new HashSet<tblParticipante>();
        }

        public int EstId { get; set; }
        public string EstDescripcion { get; set; }
        public string EstCreacion { get; set; }
        public string EstModificacion { get; set; }
        public DateTime? EstFechaCreacion { get; set; }
        public DateTime? EstFechaModificacion { get; set; }

        public virtual ICollection<tblEmpleado> tblEmpleado { get; set; }
        public virtual ICollection<tblParticipante> tblParticipante { get; set; }
    }
}