// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParqueDiversion.Entities.Entities
{
    public partial class tblParticipante
    {
        public int ParticiÍd { get; set; }
        public string ParticiNombre { get; set; }
        public string ParticiApellido { get; set; }
        public string ParticiSexo { get; set; }
        public int ParticiEstadoCivil { get; set; }
        public DateTime ParticiFechaNac { get; set; }
        public string ParticiIdentidad { get; set; }
        public string ParticiTelefono { get; set; }
        public string ParticiDireccion { get; set; }
        public string ParicitCreacion { get; set; }
        public string ParticiModificacion { get; set; }
        public DateTime? ParticiFechaCreacion { get; set; }
        public DateTime? ParticiFechaModificacion { get; set; }
        public string ParticiEstado { get; set; }

        public virtual tblEstado ParticiEstadoCivilNavigation { get; set; }
    }
}