// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParqueDiversion.Entities.Entities
{
    public partial class tbMetodosPago
    {
        public tbMetodosPago()
        {
            tbTicketsCliente = new HashSet<tbTicketsCliente>();
            tbVentasQuiosco = new HashSet<tbVentasQuiosco>();
        }

        public int pago_ID { get; set; }
        public string pago_Nombre { get; set; }
        public int? pago_Habilitado { get; set; }
        public int? pago_Estado { get; set; }
        public int? pago_UsuarioCreador { get; set; }
        public DateTime? pago_FechaCreacion { get; set; }
        public int? pago_UsuarioModificador { get; set; }
        public DateTime? pago_FechaModificacion { get; set; }

        public virtual ICollection<tbTicketsCliente> tbTicketsCliente { get; set; }
        public virtual ICollection<tbVentasQuiosco> tbVentasQuiosco { get; set; }
    }
}