// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParqueDiversion.Entities.Entities
{
    public partial class tbQuioscos
    {
        public tbQuioscos()
        {
            tbInsumosQuiosco = new HashSet<tbInsumosQuiosco>();
            tbVentasQuiosco = new HashSet<tbVentasQuiosco>();
        }

        public int quio_ID { get; set; }
        public int? area_ID { get; set; }
        public string quio_Nombre { get; set; }
        public int? empl_ID { get; set; }
        public int? regi_ID { get; set; }
        public string quio_ReferenciaUbicacion { get; set; }
        public string quio_Imagen { get; set; }
        public int? quio_Habilitado { get; set; }
        public int? quio_Estado { get; set; }
        public int? quio_UsuarioCreador { get; set; }
        public DateTime? quio_FechaCreacion { get; set; }
        public int? quio_UsuarioModificador { get; set; }
        public DateTime? quio_FechaModificacion { get; set; }

        public virtual tbAreas area { get; set; }
        public virtual tbEmpleados empl { get; set; }
        public virtual tbRegiones regi { get; set; }
        public virtual ICollection<tbInsumosQuiosco> tbInsumosQuiosco { get; set; }
        public virtual ICollection<tbVentasQuiosco> tbVentasQuiosco { get; set; }
    }
}