// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParqueDiversion.Entities.Entities
{
    public partial class tbRolesXPantallas
    {
        public int ropa_ID { get; set; }
        public int? role_ID { get; set; }
        public int? pant_ID { get; set; }
        public int? ropa_Estado { get; set; }
        public int? ropa_UsuarioCreador { get; set; }
        public DateTime? ropa_FechaCreacion { get; set; }
        public int? ropa_UsuarioModificador { get; set; }
        public DateTime? ropa_FechaModificacion { get; set; }

        public virtual tbPantallas pant { get; set; }
        public virtual tbRoles role { get; set; }
    }
}