// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParqueDiversion.Entities.Entities
{
    public partial class tbTemporizadores
    {
        public int temp_ID { get; set; }
        public int? ticl_ID { get; set; }
        public int? atra_ID { get; set; }
        public TimeSpan? temp_Expiracion { get; set; }
        public TimeSpan? temp_TiempoRestante { get; set; }
        public int? temp_FilaPosicion { get; set; }
        public int? temp_Habilitado { get; set; }
        public int? temp_Estado { get; set; }
        public int? temp_UsuarioCreador { get; set; }
        public DateTime? temp_FechaCreacion { get; set; }
        public int? temp_UsuarioModificador { get; set; }
        public DateTime? temp_FechaModificacion { get; set; }

        public virtual tbAtracciones atra { get; set; }
        public virtual tbTicketsCliente ticl { get; set; }
    }
}