// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParqueDiversion.Entities.Entities
{
    public partial class tbTipoFilas
    {
        public tbTipoFilas()
        {
            tbFilasAtraccion = new HashSet<tbFilasAtraccion>();
        }

        public int tifi_ID { get; set; }
        public string tifi_Nombre { get; set; }
        public int? tifi_Habilitado { get; set; }
        public int? tifi_Estado { get; set; }
        public int? tifi_UsuarioCreador { get; set; }
        public DateTime? tifi_FechaCreacion { get; set; }
        public int? tifi_UsuarioModificador { get; set; }
        public DateTime? tifi_FechaModificacion { get; set; }

        public virtual ICollection<tbFilasAtraccion> tbFilasAtraccion { get; set; }
    }
}