// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParqueDiversion.Entities.Entities
{
    public partial class tbVentasQuiosco
    {
        public tbVentasQuiosco()
        {
            tbVentasQuioscoDetalle = new HashSet<tbVentasQuioscoDetalle>();
        }

        public int vent_ID { get; set; }
        public int? quio_ID { get; set; }
        public int? clie_ID { get; set; }
        public int? pago_ID { get; set; }
        public int? vent_Habilitado { get; set; }
        public int? vent_Estado { get; set; }
        public int? vent_UsuarioCreador { get; set; }
        public DateTime? vent_FechaCreacion { get; set; }
        public int? vent_UsuarioModificador { get; set; }
        public DateTime? vent_FechaModificacion { get; set; }

        public virtual tbClientes clie { get; set; }
        public virtual tbMetodosPago pago { get; set; }
        public virtual tbQuioscos quio { get; set; }
        public virtual ICollection<tbVentasQuioscoDetalle> tbVentasQuioscoDetalle { get; set; }
    }
}