// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParqueDiversion.Entities.Entities
{
    public partial class tbVentasQuioscoDetalle
    {
        public int deta_ID { get; set; }
        public int? vent_ID { get; set; }
        public int? insu_ID { get; set; }
        public int? deta_Cantidad { get; set; }
        public int? deta_Habilitado { get; set; }
        public int? deta_Estado { get; set; }
        public int? deta_UsuarioCreador { get; set; }
        public DateTime? deta_FechaCreacion { get; set; }
        public int? deta_UsuarioModificador { get; set; }
        public DateTime? deta_FechaModificacion { get; set; }

        public virtual tbInsumosQuiosco insu { get; set; }
        public virtual tbVentasQuiosco vent { get; set; }
    }
}