// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParqueDiversion.Entities.Entities
{
    public partial class tbVisitantesAtraccion
    {
        public int viat_ID { get; set; }
        public int? atra_ID { get; set; }
        public int? ticl_ID { get; set; }
        public TimeSpan? viat_HoraEntrada { get; set; }

        public virtual tbAtracciones atra { get; set; }
        public virtual tbTicketsCliente ticl { get; set; }
    }
}