// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParqueDiversion.Entities.Entities
{
    public partial class VW_EstadosCiviles
    {
        public int civi_Id { get; set; }
        public string civi_Descripcion { get; set; }
        public int? civi_Estado { get; set; }
        public int? civi_UsuarioCreador { get; set; }
        public string empl_crea { get; set; }
        public DateTime? civi_FechaCreacion { get; set; }
        public int? civi_UsuarioModificador { get; set; }
        public string empl_Modifica { get; set; }
        public DateTime? civi_FechaModificacion { get; set; }
    }
}