// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParqueDiversion.Entities.Entities
{
    public partial class VW_Pantallas
    {
        public int pant_Id { get; set; }
        public string pant_Descripcion { get; set; }
        public string pant_Identificador { get; set; }
        public string pant_URL { get; set; }
        public int? pant_Estado { get; set; }
        public string pant_Icono { get; set; }
        public int? pant_UsuarioCreador { get; set; }
        public string empl_crea { get; set; }
        public DateTime? pant_FechaCreacion { get; set; }
        public int? pant_UsuarioModificador { get; set; }
        public string empl_Modifica { get; set; }
        public DateTime? pant_FechaModificacion { get; set; }
    }
}