// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParqueDiversion.Entities.Entities
{
    public partial class VW_tbFilasAtraccion
    {
        public int fiat_ID { get; set; }
        public int? tifi_ID { get; set; }
        public string tifi_Nombre { get; set; }
        public int? atra_ID { get; set; }
        public string atra_Nombre { get; set; }
    }
}