// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParqueDiversion.Entities.Entities
{
    public partial class VW_tbClientesRegistrados
    {
        public int clre_ID { get; set; }
        public string clie_Nombres { get; set; }
        public string clie_Apellidos { get; set; }
        public string clie_NombreCompleto { get; set; }
        public string clre_Usuario { get; set; }
        public string clre_Email { get; set; }
        public string clre_Clave { get; set; }
        public int? clre_Habilitado { get; set; }
        public int? clre_Estado { get; set; }
        public int? clre_UsuarioCreador { get; set; }
        public DateTime? clre_FechaCreacion { get; set; }
        public int? clre_UsuarioModificador { get; set; }
        public DateTime? clre_FechaModificacion { get; set; }
        public string empl_crea { get; set; }
        public string empl_Modifica { get; set; }
    }
}