// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParqueDiversion.Entities.Entities
{
    public partial class VW_tbFilasPosiciones
    {
        public int posicion { get; set; }
        public int fipo_ID { get; set; }
        public int? fiat_ID { get; set; }
        public int? ticl_ID { get; set; }
        public string Cliente_Nombre { get; set; }
        public string fipo_HoraIngreso { get; set; }
    }
}