// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParqueDiversion.Entities.Entities
{
    public partial class WV_tbTemporizadores
    {
        public int temp_ID { get; set; }
        public long? posicion { get; set; }
        public int? ticl_ID { get; set; }
        public string Cliente_Nombre { get; set; }
        public int? atra_ID { get; set; }
        public string atra_Nombre { get; set; }
        public string temp_Expiracion { get; set; }
        public string TiempoFaltante { get; set; }
        public string temp_Expiracion_Formateada { get; set; }
        public DateTime? temp_FechaCreacion { get; set; }
    }
}